/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-05-08 07:14:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class StudentList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Documents/struts/StudentManagementApp/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/StudentManagementApp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1681813477801L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>StudentPortal</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"public/styles/StudentList.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
   // Retrieve a session attribute
   String username = (String) session.getAttribute("username");

      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("  <img src=\"public/images/logo_opt.png\" style=\"width: 10%\" alt=\"\" />\r\n");
      out.write("  <div class=\"head-text text\">INTERRAIT STUDENT PORTAL</div>\r\n");
      out.write("  <div>\r\n");
      out.write("    <a\r\n");
      out.write("      href=\"logout.do\"\r\n");
      out.write("      class=\"head-button text\"\r\n");
      out.write("      style=\"border-right: 1px solid rgba(255, 255, 255, 0.544)\"\r\n");
      out.write("      >LOG OUT</a\r\n");
      out.write("    >\r\n");
      out.write("    <a href=\"createUserPage.do\" class=\"head-button text\"\r\n");
      out.write("      >CREATE NEW USER</a\r\n");
      out.write("    >\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"user-text\">Welcome, ");
      out.print( username );
      out.write("!</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"maintext text\" >Student List will be shown here</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("  	<th>Id</th>\r\n");
      out.write("    <th>Full Name</th>\r\n");
      out.write("    <th>College Name</th>\r\n");
      out.write("    <th>University Name</th>\r\n");
      out.write("    <th>Date of Birth</th>\r\n");
      out.write("    <th>Section</th>\r\n");
      out.write("    <th>Stream</th>\r\n");
      out.write("    <th>Gender</th>\r\n");
      out.write("    <th>Student Email</th>\r\n");
      out.write("    <th>Delete</th>\r\n");
      out.write("    <th>Update</th>\r\n");
      out.write("    \r\n");
      out.write("  </tr>\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div  > <h2>InterraIT student Portal</h2></div>\r\n");
      out.write("    <div id=\"footer-text\" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid nobis molestiae exercitationem dolor dolore voluptate tempore corrupti eligendi modi consequuntur quidem adipisci, deleniti sapiente? Vel inventore quo eos unde vitae.</div>\r\n");
      out.write("    <div id=\"socials\">\r\n");
      out.write("        <div><span class=\"material-symbols-outlined\"> mail</span></div>\r\n");
      out.write("        <div><span class=\"material-symbols-outlined\">phone_in_talk</span></div>\r\n");
      out.write("        <div><span class=\"material-symbols-outlined\"> sms</span></div>\r\n");
      out.write("        <div><span class=\"material-symbols-outlined\">contact_page</span></div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>All rights reserves @2023</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	var isUpdateOn=false;\r\n");
      out.write("	function deleteStudent(id){\r\n");
      out.write("		console.log(id)\r\n");
      out.write("		 $.ajax({\r\n");
      out.write("		    type: \"GET\",\r\n");
      out.write("		    url: \"deleteStudent.do\",\r\n");
      out.write("		    data: { id:id },\r\n");
      out.write("		    success: function(response) {\r\n");
      out.write("		      // handle success response\r\n");
      out.write("		      //location.reload();\r\n");
      out.write("		      document.getElementById(id+\"-row\").style.display=\"none\";\r\n");
      out.write("		      document.getElementById(id+\"-form\").style.display=\"none\";\r\n");
      out.write("		      console.log(\"Student deleted successfully.\");\r\n");
      out.write("		      location.reload();\r\n");
      out.write("		    },\r\n");
      out.write("		    error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("		      // handle error response\r\n");
      out.write("		      alert(\"Error deleting student:\");\r\n");
      out.write("		    }\r\n");
      out.write("		  });	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function editStudent(id){\r\n");
      out.write("		if(!isUpdateOn){\r\n");
      out.write("			isUpdateOn=true;\r\n");
      out.write("			console.log(\"#\"+id+\"-row\")\r\n");
      out.write("			document.getElementById(id+\"-row\").style.display=\"none\";\r\n");
      out.write("			document.getElementById(id+\"-form\").style.display=\"table-row\";\r\n");
      out.write("			gender=document.getElementById(id+\"gender-row\").innerHTML;\r\n");
      out.write("			console.log(gender)\r\n");
      out.write("			var genderRadio = document.querySelector('input[name=\"'+id+'gender\"][value=\"' + gender + '\"]');\r\n");
      out.write("			console.log(genderRadio)\r\n");
      out.write("			if (genderRadio) {\r\n");
      out.write("			  genderRadio.checked = true;\r\n");
      out.write("			}\r\n");
      out.write("		}else{\r\n");
      out.write("			alert(\"Update one row at one time\")\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	function updateStudent(id){\r\n");
      out.write("		\r\n");
      out.write("			isUpdateOn=false;\r\n");
      out.write("			\r\n");
      out.write("			var studentData=getData(id)\r\n");
      out.write("			console.log(studentData)\r\n");
      out.write("			console.log(\"date out\",validate_date(studentData.studentId))\r\n");
      out.write("			if(!validate_date(studentData.studentId)){\r\n");
      out.write("				\r\n");
      out.write("				alert(\"Input date can't be greater than current date\")\r\n");
      out.write("				return \"failure\";\r\n");
      out.write("			}\r\n");
      out.write("			var isOk=validate(studentData)\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			if(!isOk) {\r\n");
      out.write("				alert(\"Field should not be empty\")\r\n");
      out.write("				return \"failure\";\r\n");
      out.write("			}\r\n");
      out.write("			console.log(studentData)\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("		    type: \"POST\",\r\n");
      out.write("		    url: \"updateStudent.do\",\r\n");
      out.write("		    data: studentData,\r\n");
      out.write("		    success: function(response) {\r\n");
      out.write("		      // handle success response\r\n");
      out.write("			document.getElementById(id+\"-row\").style.display=\"table-row\";\r\n");
      out.write("			document.getElementById(id+\"-form\").style.display=\"none\";\r\n");
      out.write("		      location.reload();\r\n");
      out.write("		    },\r\n");
      out.write("		    error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("		      // handle error response\r\n");
      out.write("		      alert(\"Error updating student:\");\r\n");
      out.write("		    }\r\n");
      out.write("		  });	\r\n");
      out.write("			return \"success\";\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function getData(id){\r\n");
      out.write("		var student = {};\r\n");
      out.write("		console.log(id)\r\n");
      out.write("		\r\n");
      out.write("		// get input fields using their name attribute and assign their values to object properties\r\n");
      out.write("		student.studentId=id;\r\n");
      out.write("		student.fullName = document.getElementById(id+\"full-name\").value;\r\n");
      out.write("		student.collegeName = document.getElementById(id+\"college-name\").value;\r\n");
      out.write("		student.universityName = document.getElementById(id+\"university-name\").value;\r\n");
      out.write("		student.dateOfBirth = document.getElementById(id+\"date-of-birth\").value;\r\n");
      out.write("		student.section = document.getElementById(id+\"section\").value;\r\n");
      out.write("		student.stream = document.getElementById(id+\"department\").value;\r\n");
      out.write("		student.gender = document.querySelector('input[name=\"'+id+'gender\"]:checked').value;\r\n");
      out.write("		student.studentEmail = document.getElementById(id+\"email\").innerHTML;\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		return student;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function validate(studentList){\r\n");
      out.write("		\r\n");
      out.write("		for (let key in studentList) {\r\n");
      out.write("			 if(studentList[key].length==0){\r\n");
      out.write("				 return false;\r\n");
      out.write("			 }\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function  validate_date(id) {\r\n");
      out.write("		  // Get the date input field\r\n");
      out.write("		  var dateInput = $(\"#\"+id+\"date-of-birth\");\r\n");
      out.write("\r\n");
      out.write("		  // Add an event listener to the date input field\r\n");
      out.write("		 \r\n");
      out.write("		    // Get the value of the date input field\r\n");
      out.write("		    var inputValue = dateInput.val();\r\n");
      out.write("\r\n");
      out.write("		    // Convert the input value to a Date object\r\n");
      out.write("		    var inputDate = new Date(inputValue);\r\n");
      out.write("\r\n");
      out.write("		    // Get the current date\r\n");
      out.write("		    var currentDate = new Date();\r\n");
      out.write("\r\n");
      out.write("		    // Compare the input date with the current date\r\n");
      out.write("		    console.log(inputDate , currentDate,inputDate > currentDate)\r\n");
      out.write("		    if (inputDate >= currentDate) {\r\n");
      out.write("		      // Show an error message\r\n");
      out.write("		      return false;\r\n");
      out.write("		    } else {\r\n");
      out.write("		      // Clear the error message\r\n");
      out.write("		     return true;\r\n");
      out.write("		    }\r\n");
      out.write("		 \r\n");
      out.write("		}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/StudentList.jsp(55,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("student");
      // /WEB-INF/views/StudentList.jsp(55,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/StudentList.jsp(55,2) '${studentList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${studentList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <tr id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-row\"  > \r\n");
            out.write("    	<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>  \r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.collegeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.universityName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.dateOfBirth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.section}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.stream}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("gender-row\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>\r\n");
            out.write("      	<button onclick=\"deleteStudent('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"   ><span class=\"material-symbols-outlined\">\r\n");
            out.write("delete\r\n");
            out.write("</span></button>\r\n");
            out.write("      </td>\r\n");
            out.write("      <td>\r\n");
            out.write("      	<button onclick=\"editStudent('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"   ><span class=\"material-symbols-outlined\">\r\n");
            out.write("edit\r\n");
            out.write("</span></button>\r\n");
            out.write("      </td>\r\n");
            out.write("    </tr>\r\n");
            out.write("  	\r\n");
            out.write("  	<tr  class=\"hidden\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-form\"  >\r\n");
            out.write("  	\r\n");
            out.write("  	 <td> <input type=\"text\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("student-id\" name=\"fullName\" value= \" ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  ></td>\r\n");
            out.write("      <td> <input type=\"text\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("full-name\" name=\"fullName\" value= \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  ></td>\r\n");
            out.write("      <td><input type=\"text\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("college-name\" name=\"collegeName\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.collegeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" ></td>\r\n");
            out.write("      <td><input type=\"text\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("university-name\" name=\"universityName\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.universityName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" ></td>\r\n");
            out.write("      <td><input type=\"date\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("date-of-birth\" name=\"dateOfBirth\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.dateOfBirth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" ></td>\r\n");
            out.write("      <td><input type=\"text\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("section\" name=\"section\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.section}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" ></td>\r\n");
            out.write("      <td> <input type=\"text\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("department\" name=\"stream\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.stream}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" ></td>\r\n");
            out.write("      <td class=\"radio-button\" >\r\n");
            out.write("      	  <input  type=\"radio\"   id=\"male\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("gender\" value=\"male\">\r\n");
            out.write("		  <label for=\"male\">male</label>\r\n");
            out.write("		  <input  type=\"radio\"   id=\"female\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("gender\" value=\"female\">\r\n");
            out.write("		  <label for=\"female\">female</label>\r\n");
            out.write("	  </td>\r\n");
            out.write("      <td id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("email\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("      <td>\r\n");
            out.write("      	 <button onclick=\"deleteStudent('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"   ><span class=\"material-symbols-outlined\">\r\n");
            out.write("delete\r\n");
            out.write("</span></button>\r\n");
            out.write("      </td>\r\n");
            out.write("      <td><button onclick=\"updateStudent('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"   ><span class=\"material-symbols-outlined\">\r\n");
            out.write("frame_reload\r\n");
            out.write("</span></button>\r\n");
            out.write("     \r\n");
            out.write("      	\r\n");
            out.write("      </td>\r\n");
            out.write("  \r\n");
            out.write("    </tr>\r\n");
            out.write("    \r\n");
            out.write("  \r\n");
            out.write("  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
